name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 SSH 密钥
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    # 同步文件到服务器
    - name: Sync files to server
      run: |
        rsync -avz --delete \
          --exclude '.git' \
          -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
          ./ \
          ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}

    # 确保 deploy.sh 可执行
    - name: Ensure deploy.sh is executable
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "chmod +x ${{ secrets.TARGET }}/deploy.sh"

    # 执行远程部署脚本
    - name: Run deploy script
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "bash ${{ secrets.TARGET }}/deploy.sh"